# Neural Networks From Scratch

This notebook implements the core building blocks of a neural network using only NumPy.

## Contents

1. Environment Setup
2. Single Neuron
3. Multiple Neurons
4. Dense Layer
5. ReLU Activation
6. Softmax Activation
7. Cross Entropy Loss
8. Forward Propagation
9. Mean Squared Error
10. Binary Cross Entropy
11. Derivatives
12. Backpropagation
13. Gradient Descent
14. Conclusion

## 1. Environment Setup

In [1]:
import sys
import numpy as np
import matplotlib 

In [2]:
print(sys.version)
print(np.__version__)
print(matplotlib.__version__)

3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]
1.26.4
3.10.7


## 2. Single Neuron

In [3]:
# Single neuron with linear activation function & constant values
bias = 2
inputs = [1,2,3,2.5] ## Inputs considered here can be from hidden layers too not just input layer
weights = [0.2,0.8,-0.5,1.0]
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] +bias
output

4.8

In [4]:
# Layer where there are four inputs & three outputs
bias = [2,3,4]
inputs = [0.4,0.8,-0.7,0.6]
weights_one = [0.2,-0.3,0.33,0.98]
weights_two = [0.6,0.76,0.85,0.34]
weights_three = [0.39,0.23,0.56,0.74]
output_one = inputs[0]*weights_one[0] + inputs[1]*weights_one[1] + inputs[2]*weights_one[2] + inputs[3]*weights_one[3] +bias[0]
output_two = inputs[0]*weights_two[0] + inputs[1]*weights_two[1] + inputs[2]*weights_two[2] + inputs[3]*weights_two[3] +bias[1]
ouput_three = inputs[0]*weights_three[0] + inputs[1]*weights_three[1] + inputs[2]*weights_three[2] + inputs[3]*weights_three[3] +bias[2]
output_layer = [output_one,output_two,ouput_three]
print(output_layer)

[2.197, 3.4570000000000003, 4.392]


In [5]:
# Implementing neuron & layer from scratch using numpy
bias = 2
inputs = [0.4,0.8,-0.7,0.6]
weights = [0.2,0.8,-0.5,1.0]
output = np.dot(inputs, weights) +bias
print(output)

3.67


In [6]:
bias = [2,3,4]
inputs = [0.4,0.8,-0.7,0.6]
weights = [weights_one,weights_two,weights_three]
output = np.dot(weights,inputs)+bias ## weights were ordered before due to indexing reasons 
output

array([2.197, 3.457, 4.392])

## 3. Multiple Neurons

In [7]:
# Implementation of NN with inputs having multiple features
bias = [2,3,4]
inputs = [[0.4,0.8,-0.7,0.6],[0.2,0.89,0.56,0.21],[0.45,0.32,0.66,0.78]]
weights = [weights_one,weights_two,weights_three]
output = np.dot(inputs,np.array(weights).T) + bias
print(output)

[[2.197  3.457  4.392 ]
 [2.1636 4.3438 4.7517]
 [2.9762 4.3394 5.1959]]


## 4. Dense Layer

In [8]:
class Dense_Layer:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.1*np.random.randn(n_inputs,n_neurons)
        self.bias = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.bias

## 5. ReLU Activation

In [9]:
# Implementing relu activation function 
output = [-0.2,3.3,-0.77,0.54,4.23]
def Activated_relu(output):
    a=[]
    for i in output:
        if i > 0:
            a.append(i)
        else:
            a.append(0)
    return a
Activated_relu(output)

[0, 3.3, 0, 0.54, 4.23]

In [10]:
def Activated_relu(inputs):
    outputs=[]
    for i in inputs:
        outputs.append(np.max(i,0))
    return outputs

In [11]:
def relu_activation_fun(x):
    return np.maximum(x,0)

## 6. Softmax Activation

In [12]:
# Implementing Softmax function from scratch
output_layer = [2.2,3.5,7.5,8.8]
def Softmax_Output(output):
    Softmax_Output_layer=[]
    total=0
    for i in output:
        total= total + np.exp(i)
    for i in output:
        value = np.exp(i)
        Softmax_Output_layer.append(value/total)
    return Softmax_Output_layer

Softmax_Output(output_layer)

[0.0010637151596086963,
 0.0039030864904482615,
 0.21310130179783257,
 0.7819318965521105]

## 7. Cross Entropy Loss

In [13]:
# Implementing cross-entropy loss from scratch
output_layer = [0.7,0.2,0.1] # softmaxed already
target_output = [1,0,0]
loss = -(target_output[0]*np.log(output_layer[0])+
         target_output[1]*np.log(output_layer[1])+
         target_output[2]*np.log(output_layer[2]))
print(loss)

0.35667494393873245


In [14]:
def cross_entropy_loss(y_pred, y_true):
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)
    return -np.sum(y_true * np.log(y_pred))

## 8. Forward Propagation

In [15]:
## Single layer forward pass
inputs=[2,3]
weights=[5,6]
bias = 4
output = np.dot(inputs,weights)+bias
# no activation function was applied
output

32

In [16]:
## NN with a hidden layer
inputs=[2,3]
weights_one=[5,6]
weights_two = [6,7]
bias_one = 4
bias_two = 2
output_one = relu_activation_fun(np.dot(inputs,weights_one) +bias_one)
output_two = relu_activation_fun(np.dot(inputs,weights_two)+bias_two)
inputs_two = [output_one,output_two]
weights_hiddenlayer= [2,3]
bias = 0
output_layer = relu_activation_fun(np.dot(inputs_two,weights)+ bias)
output_layer

370

In [17]:
## Generalising the forward propagation
def forward_propgation(inputs,weights,bias):
    output_layer=[]
    output_layer.append(np.dot(weights,inputs)+bias)
    return output_layer ## This furthur can be used as input for layer ahead it

## 9. Mean Squared Error

In [18]:
## mse
def mean_squared_error(y_true,y_pred):
    error = []
    e = (y_true - y_pred)**2
    error.append(e)
    error_generated = np.mean(error)
    return error

In [19]:
def mean_squared_error(y_true,y_pred):
    return np.mean(((y_true - y_pred)**2))

## 10. Binary Cross Entropy

In [20]:
def binary_cross_entropy(y_true,y_pred):
    error = -(y_true*np.log(y_pred) + (1-y_true)*np.log(1-y_pred))
    return error

## 11. Derivatives

In [21]:
def derived_mse(y_true,y_pred):
    n = len(y_true)
    error = (2/n)*(y_true-y_pred)
    return error

In [22]:
def derived_bce(y_true,y_pred):
    error= (y_pred-y_true) / y_pred * (1-y_pred)
    return error

## 12. Backpropagation

In [23]:
def backpropagation(y_pred, y_true, inputs):
    dz_dw = inputs
    dy_dz = y_pred * (1 - y_pred)
    dL_dy = 2 * (y_pred - y_true)
    dL_dw = dL_dy * dy_dz * dz_dw
    return dL_dw

## 13. Gradient Descent

In [24]:
def gradient_descent(m,b,y_true,y_pred,inputs, learning_rate):
    n = len(y_true)
    dmse_dm = 2/n * np.sum((-inputs)*(y_true-y_pred))
    dmse_db = 2/n * np.sum((y_pred - y_true))
    m = m - learning_rate*dmse_dm
    b = b - learning_rate*dmse_db
    return m,b

## 14. Conclusion

In this notebook we implemented:

- Dense Layer
- ReLU
- Softmax
- Cross Entropy Loss
- MSE
- BCE
- Forward Propagation
- Backpropagation
- Gradient Descent

without using TensorFlow or PyTorch.

## References

- Neural Networks from Scratch
- Deep Learning (Ian Goodfellow)
- NumPy Documentation